# models/sources.yml
version: 2

sources:
  - name: raw_data
    database: postgres
    schema: public
    tables:
      - name: cleaned_dataset
  - name: b2b
    database: postgres
    schema: public
    tables:
      - name: dim_b2b
  - name: courier
    database: postgres
    schema: public
    tables:
      - name: dim_courier_status
  - name: date
    database: postgres
    schema: public
    tables:
      - name: dim_date
  - name: fulfilled_by
    database: postgres
    schema: public
    tables:
      - name: dim_fulfilled_by
  - name: fulfilment
    database: postgres
    schema: public
    tables:
      - name: dim_fulfilment
  - name: location
    database: postgres
    schema: public
    tables:
      - name: dim_location
  - name: status
    database: postgres
    schema: public
    tables:
      - name: dim_order_status
  - name: product
    database: postgres
    schema: public
    tables:
      - name: dim_product
  - name: promotion
    database: postgres
    schema: public
    tables:
      - name: dim_promotion
  - name: sales_channel
    database: postgres
    schema: public
    tables:
      - name: dim_sales_channel
  - name: service_channel
    database: postgres
    schema: public
    tables:
      - name: dim_shiment_service_level
